export { Navigation } from './Navigation'
export { Hero } from './Hero'
export { Projects } from './Projects'
export { About } from './About'
export { Contact } from './Contact'
export { Footer } from './Footer'
